/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'tShirtShortsSize' : IDL.Text,
  'studentName' : IDL.Text,
  'dobMonth' : IDL.Nat,
  'dobDate' : IDL.Nat,
  'food' : IDL.Text,
  'game' : IDL.Text,
  'dobYear' : IDL.Nat,
  'mobileNo' : IDL.Text,
  'blazerSize' : IDL.Text,
  'shoeSize' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'gender' : IDL.Text,
  'timestamp' : IDL.Int,
  'trackSuitSize' : IDL.Text,
  'studentClass' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const RegistrationInput = IDL.Record({
  'tShirtShortsSize' : IDL.Text,
  'studentName' : IDL.Text,
  'dobMonth' : IDL.Nat,
  'dobDate' : IDL.Nat,
  'food' : IDL.Text,
  'game' : IDL.Text,
  'dobYear' : IDL.Nat,
  'mobileNo' : IDL.Text,
  'blazerSize' : IDL.Text,
  'shoeSize' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'gender' : IDL.Text,
  'trackSuitSize' : IDL.Text,
  'studentClass' : IDL.Text,
  'ageGroup' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getRegistrationByAdmissionNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Registration)],
      ['query'],
    ),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitRegistration' : IDL.Func([RegistrationInput], [IDL.Nat], []),
  'updateRegistration' : IDL.Func([IDL.Nat, RegistrationInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'tShirtShortsSize' : IDL.Text,
    'studentName' : IDL.Text,
    'dobMonth' : IDL.Nat,
    'dobDate' : IDL.Nat,
    'food' : IDL.Text,
    'game' : IDL.Text,
    'dobYear' : IDL.Nat,
    'mobileNo' : IDL.Text,
    'blazerSize' : IDL.Text,
    'shoeSize' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'gender' : IDL.Text,
    'timestamp' : IDL.Int,
    'trackSuitSize' : IDL.Text,
    'studentClass' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const RegistrationInput = IDL.Record({
    'tShirtShortsSize' : IDL.Text,
    'studentName' : IDL.Text,
    'dobMonth' : IDL.Nat,
    'dobDate' : IDL.Nat,
    'food' : IDL.Text,
    'game' : IDL.Text,
    'dobYear' : IDL.Nat,
    'mobileNo' : IDL.Text,
    'blazerSize' : IDL.Text,
    'shoeSize' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'gender' : IDL.Text,
    'trackSuitSize' : IDL.Text,
    'studentClass' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getRegistrationByAdmissionNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitRegistration' : IDL.Func([RegistrationInput], [IDL.Nat], []),
    'updateRegistration' : IDL.Func(
        [IDL.Nat, RegistrationInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };