/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'tShirtShortsSize' : IDL.Text,
  'studentName' : IDL.Text,
  'dobMonth' : IDL.Nat,
  'dobDate' : IDL.Nat,
  'food' : IDL.Text,
  'game' : IDL.Text,
  'dobYear' : IDL.Nat,
  'mobileNo' : IDL.Text,
  'blazerSize' : IDL.Text,
  'shoeSize' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'gender' : IDL.Text,
  'timestamp' : IDL.Int,
  'trackSuitSize' : IDL.Text,
  'studentClass' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const RegistrationInput = IDL.Record({
  'tShirtShortsSize' : IDL.Text,
  'studentName' : IDL.Text,
  'dobMonth' : IDL.Nat,
  'dobDate' : IDL.Nat,
  'food' : IDL.Text,
  'game' : IDL.Text,
  'dobYear' : IDL.Nat,
  'mobileNo' : IDL.Text,
  'blazerSize' : IDL.Text,
  'shoeSize' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'gender' : IDL.Text,
  'trackSuitSize' : IDL.Text,
  'studentClass' : IDL.Text,
  'ageGroup' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getRegistrationByAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Opt(Registration)], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitRegistration' : IDL.Func([RegistrationInput], [IDL.Nat], []),
  'updateRegistration' : IDL.Func([IDL.Nat, RegistrationInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'tShirtShortsSize' : IDL.Text,
    'studentName' : IDL.Text,
    'dobMonth' : IDL.Nat,
    'dobDate' : IDL.Nat,
    'food' : IDL.Text,
    'game' : IDL.Text,
    'dobYear' : IDL.Nat,
    'mobileNo' : IDL.Text,
    'blazerSize' : IDL.Text,
    'shoeSize' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'gender' : IDL.Text,
    'timestamp' : IDL.Int,
    'trackSuitSize' : IDL.Text,
    'studentClass' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const RegistrationInput = IDL.Record({
    'tShirtShortsSize' : IDL.Text,
    'studentName' : IDL.Text,
    'dobMonth' : IDL.Nat,
    'dobDate' : IDL.Nat,
    'food' : IDL.Text,
    'game' : IDL.Text,
    'dobYear' : IDL.Nat,
    'mobileNo' : IDL.Text,
    'blazerSize' : IDL.Text,
    'shoeSize' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'gender' : IDL.Text,
    'trackSuitSize' : IDL.Text,
    'studentClass' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRegistration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getRegistrationByAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Opt(Registration)], ['query']),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitRegistration' : IDL.Func([RegistrationInput], [IDL.Nat], []),
    'updateRegistration' : IDL.Func([IDL.Nat, RegistrationInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };