/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegistrationInput {
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl?: string;
    admissionNumber: string;
    fatherName: string;
    gender: string;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
}
export interface Registration {
    id: bigint;
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl?: string;
    admissionNumber: string;
    fatherName: string;
    gender: string;
    timestamp: bigint;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
}
export interface backendInterface {
    deleteRegistration(id: bigint): Promise<boolean>;
    getRegistrationByAdmissionNumber(admissionNumber: string): Promise<Registration | null>;
    getRegistrationCount(): Promise<bigint>;
    getRegistrations(): Promise<Array<Registration>>;
    isCallerAdmin(): Promise<boolean>;
    submitRegistration(input: RegistrationInput): Promise<bigint>;
    updateRegistration(id: bigint, input: RegistrationInput): Promise<boolean>;
}
import type { Registration as _Registration, RegistrationInput as _RegistrationInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteRegistration(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegistration(arg0);
            return result;
        }
    }
    async getRegistrationByAdmissionNumber(arg0: string): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationByAdmissionNumber(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationByAdmissionNumber(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationCount();
            return result;
        }
    }
    async getRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrations();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrations();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitRegistration(arg0: RegistrationInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(to_candid_RegistrationInput_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(to_candid_RegistrationInput_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRegistration(arg0: bigint, arg1: RegistrationInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistration(arg0, to_candid_RegistrationInput_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistration(arg0, to_candid_RegistrationInput_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Registration_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Registration): Registration {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registration]): Registration | null {
    return value.length === 0 ? null : from_candid_Registration_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl: [] | [string];
    admissionNumber: string;
    fatherName: string;
    gender: string;
    timestamp: bigint;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
}): {
    id: bigint;
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl?: string;
    admissionNumber: string;
    fatherName: string;
    gender: string;
    timestamp: bigint;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
} {
    return {
        id: value.id,
        tShirtShortsSize: value.tShirtShortsSize,
        studentName: value.studentName,
        dobMonth: value.dobMonth,
        dobDate: value.dobDate,
        food: value.food,
        game: value.game,
        dobYear: value.dobYear,
        mobileNo: value.mobileNo,
        blazerSize: value.blazerSize,
        shoeSize: value.shoeSize,
        motherName: value.motherName,
        photoUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.photoUrl)),
        admissionNumber: value.admissionNumber,
        fatherName: value.fatherName,
        gender: value.gender,
        timestamp: value.timestamp,
        trackSuitSize: value.trackSuitSize,
        studentClass: value.studentClass,
        ageGroup: value.ageGroup
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Registration>): Array<Registration> {
    return value.map((x)=>from_candid_Registration_n2(_uploadFile, _downloadFile, x));
}
function to_candid_RegistrationInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationInput): _RegistrationInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl?: string;
    admissionNumber: string;
    fatherName: string;
    gender: string;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
}): {
    tShirtShortsSize: string;
    studentName: string;
    dobMonth: bigint;
    dobDate: bigint;
    food: string;
    game: string;
    dobYear: bigint;
    mobileNo: string;
    blazerSize: string;
    shoeSize: string;
    motherName: string;
    photoUrl: [] | [string];
    admissionNumber: string;
    fatherName: string;
    gender: string;
    trackSuitSize: string;
    studentClass: string;
    ageGroup: string;
} {
    return {
        tShirtShortsSize: value.tShirtShortsSize,
        studentName: value.studentName,
        dobMonth: value.dobMonth,
        dobDate: value.dobDate,
        food: value.food,
        game: value.game,
        dobYear: value.dobYear,
        mobileNo: value.mobileNo,
        blazerSize: value.blazerSize,
        shoeSize: value.shoeSize,
        motherName: value.motherName,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        admissionNumber: value.admissionNumber,
        fatherName: value.fatherName,
        gender: value.gender,
        trackSuitSize: value.trackSuitSize,
        studentClass: value.studentClass,
        ageGroup: value.ageGroup
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
